name: Manual CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        type: choice
        options:
          - staging
          - staging-canary
          - prod
          - prod-canary
        required: true
        default: staging
#      staging:
#        description: "Deploy to staging"
#        type: boolean
#        required: true
#      staging_canary:
#        description: "Deploy to staging-canary"
#        type: boolean
#        required: true
#      prod:
#        description: "Deploy to prod"
#        type: boolean
#        required: true
#      prod_canary:
#        description: "Deploy to prod-canary"
#        type: boolean
#        required: true

jobs:
  log:
    name: Logs inputs
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: echo "${{ github.event.inputs.environment }} and ${{ github.ref }}"

# --- Staging canary --- #

  environment_staging:
    if: github.event.inputs.environment == 'staging'
    name: 'Environment staging'
    runs-on: [self-hosted]

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch deployment script
        uses: actions/github-script@v6.0.0
        with:
          script: |
            const script = require('./deploy_staging.js')
            await script({github, context, core})
        
# --- Staging canary --- #

  environment_staging_canary:
    if: github.event.inputs.environment == 'staging-canary'
    name: 'Environment staging-canary'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch deployment script
        uses: actions/github-script@v6.0.0
        with:
          script: |
            const script = require('./deploy_staging-canary.js')
            await script({github, context, core})
        
# --- Prod --- #

  environment_prod:
    if: github.event.inputs.environment == 'prod'
    name: 'Environment prod'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch deployment script
        uses: actions/github-script@v6.0.0
        with:
          script: |
            const script = require('./deploy_prod.js')
            await script({github, context, core})
        
# --- Prod canary --- #

  environment_prod_canary:
    if: github.event.inputs.environment == 'prod-canary'
    name: 'Environment prod-canary'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch deployment script
        uses: actions/github-script@v6.0.0
        with:
          script: |
            const script = require('./deploy_prod-canary.js')
            await script({github, context, core})
