name: Manual CI

on:
  workflow_dispatch:
    inputs:
      setup:
        description: "Choose setup"
        type: choice
        options:
          - A
          - B
        required: true
        default: A
      prode:
        description: "Deploy to prod"
        type: boolean
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  log:
    name: Logs inputs
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: echo "${{ github.event.inputs.setup }}"
      - name: Prod
        run: echo "${{ github.event.inputs.prod }}"
      - name: Setup
        run: echo "${{ github.event.inputs.environment }}"

  setup_a:
    if: github.event.inputs.setup == 'A'
    name: 'Setup A'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch setup
        run: ./setup_a.sh

  setup_b:
    if: github.event.inputs.setup == 'B'
    name: 'Setup B'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch setup
        run: ./setup_b.sh
