name: Manual CI

on:
  workflow_dispatch:
    inputs:
      setup:
        description: "Choose setup"
        type: choice
        options:
          - staging
          - staging-canary
          - prod
          - prod-canary
        required: true
        default: staging
      staging:
        description: "Deploy to staging"
        type: boolean
        required: true
      staging_canary:
        description: "Deploy to staging-canary"
        type: boolean
        required: true
      prod:
        description: "Deploy to prod"
        type: boolean
        required: true
      prod_canary:
        description: "Deploy to prod-canary"
        type: boolean
        required: true

jobs:
  log:
    name: Logs inputs
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: echo "${{ github.event.inputs.setup }}"
      - name: Staging
        run: echo "${{ github.event.inputs.staging }}"
      - name: Staging-canary
        run: echo "${{ github.event.inputs.staging_canary }}"
      - name: Prod
        run: echo "${{ github.event.inputs.prod }}"
      - name: Prod-canary
        run: echo "${{ github.event.inputs.prod_canary }}"

  setup_a:
    if: github.event.inputs.setup == 'A'
    name: 'Setup A'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch setup
        run: ./setup_a.sh

  setup_b:
    if: github.event.inputs.setup == 'B'
    name: 'Setup B'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout to the code" 
        uses: actions/checkout@v3

      - name: Launch setup
        run: ./setup_b.sh
